// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {main} from '../models';

export function GetMeilisearchHealth(): Promise<boolean> {
  return window['go']['main']['App']['GetMeilisearchHealth']();
}

export function IndexDirectory(arg1: string): Promise<void> {
  return window['go']['main']['App']['IndexDirectory'](arg1);
}

export function IndexFile(arg1: string): Promise<void> {
  return window['go']['main']['App']['IndexFile'](arg1);
}

export function OpenFile(arg1: string): Promise<void> {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Search(arg1: string, arg2: number): Promise<main.SearchResponse> {
  return window['go']['main']['App']['Search'](arg1, arg2);
}
