// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMeilisearchHealth():Promise<boolean>;

export function IndexDirectory(arg1:string):Promise<void>;

export function IndexFile(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<main.SearchResponse>;
