// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMeilisearchHealth() {
  return window['go']['main']['App']['GetMeilisearchHealth']();
}

export function IndexDirectory(arg1) {
  return window['go']['main']['App']['IndexDirectory'](arg1);
}

export function IndexFile(arg1) {
  return window['go']['main']['App']['IndexFile'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}
